apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: micro
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
      - image: k8s.gcr.io/busybox
        name: micro
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; while true; do sleep 29; done;
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 30
          periodSeconds: 5
        ports:
        - containerPort: 80
data:
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs