apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monolith
  namespace: argocd
  labels:
    app.kubernetes.io/instance: apps-deployments
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/fai-prive/argocd-test.git
    targetRevision: HEAD
    path: monolith
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: micro
  namespace: argocd
  labels:
    app.kubernetes.io/instance: apps-deployments
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/fai-prive/argocd-test.git
    targetRevision: HEAD
    path: micro
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}