apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monolith
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/fai-prive/argocd-test.git
    targetRevision: HEAD
    path: monolith
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}