###### This is for consul
consul:
  global:
    datacenter: sit_sg

  server:
    replicas: 1
    bootstrapExpect: 1
    disruptionBudget:
      maxUnavailable: 0
    storage: 8Gi
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    securityContext:
      runAsNonRoot: false
      runAsGroup: 0
      runAsUser: 0
      fsGroup: 0
  client:
    enabled: true
    replicas: 2
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    securityContext:
      runAsNonRoot: false
      runAsGroup: 0
      runAsUser: 0
      fsGroup: 0
  ui:
    service:
      enabled: true
      type: ClusterIP

########### This is for vault

vault:
  server:
    affinity: ""
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi

    #postStart:
    #- /bin/sh
    #- -c
    #- |
    #   hostname=`hostname`
    #   if [ $hostname == "vault-consul-0" ]; then
    #      sleep 60
    #      vault operator init > /tmp/data.txt
    #   else
    #      echo "hi"
    #   fi
    #extraSecretEnvironmentVars:
    #  - envName: AWS_ACCESS_KEY_ID
    #    secretName: vault
    #    secretKey: AWS_ACCESS_KEY_ID
    #  - envName: AWS_SECRET_ACCESS_KEY
    #    secretName: vault
    #    secretKey: AWS_SECRET_ACCESS_KEY
    ha:
      enabled: true
      #replicas: 3
      config: |
        ui = true
        seal "awskms" {
           region = "ap-southeast-1"
           kms_key_id = "1730aba7-a908-42b1-8659-5f8b69d726d8"
        }
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "consul" {
          path = "vault"
          address = "HOST_IP:8500"
        }
        service_registration "kubernetes" {}
    serviceAccount:
      create: true
      name: vault-sa
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::148405664278:role/irsa-role20211117140215092400000002

  ui:
    enabled: true
    serviceType: ClusterIP
