###### This is for consul
consul:
  global:
    datacenter: sit_sg

  client:
    enabled: true

  server:
    replicas: 1
    bootstrapExpect: 1
    disruptionBudget:
      maxUnavailable: 0

########### This is for vault

vault:
  server:
    affinity: ""
    ha:
      enabled: true